# Generated by Django 3.2.4 on 2021-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event_date',
            field=models.DateField(),
        ),
    ]
